[package]
name = "heat_probe"
publish = false
edition = "2024"
description = "Heat-map probe tool for zombie_rs"

[dependencies]
zombie_rs = { path = "../zombie_rs" }
eframe = { version = "0.27", default-features = false, features = ["wgpu", "default_fonts", "wayland", "x11"] }
rayon = "1.10"
